"""Type stubs for the MAT bindings (ADR-185 P3).

Present only when the wheel is built with the ``[mat]`` extra.
"""

from __future__ import annotations

import enum

class DisasterType(enum.Enum):
    BuildingCollapse = 0
    Earthquake = 1
    Landslide = 2
    Avalanche = 3
    Flood = 4
    MineCollapse = 5
    Industrial = 6
    TunnelCollapse = 7
    Unknown = 8
    def __repr__(self) -> str: ...

class TriageStatus(enum.Enum):
    Immediate = 0
    Delayed = 1
    Minor = 2
    Deceased = 3
    Unknown = 4
    @property
    def priority(self) -> int: ...
    def __repr__(self) -> str: ...

class VitalSignsReading:
    @property
    def breathing_rate_bpm(self) -> float | None: ...
    @property
    def heartbeat_rate_bpm(self) -> float | None: ...
    @property
    def movement_intensity(self) -> float: ...
    @property
    def confidence(self) -> float: ...
    def __repr__(self) -> str: ...

class Survivor:
    @property
    def id(self) -> str: ...
    @property
    def triage_status(self) -> TriageStatus: ...
    @property
    def confidence(self) -> float: ...
    @property
    def location(self) -> tuple[float, float, float] | None: ...
    @property
    def latest_vitals(self) -> VitalSignsReading | None: ...
    def __repr__(self) -> str: ...

class DisasterConfig:
    def __init__(
        self,
        disaster_type: DisasterType,
        sensitivity: float = ...,
        confidence_threshold: float = ...,
        max_depth: float = ...,
        scan_interval_ms: int = ...,
    ) -> None: ...
    @property
    def sensitivity(self) -> float: ...
    @property
    def confidence_threshold(self) -> float: ...
    @property
    def max_depth(self) -> float: ...
    def __repr__(self) -> str: ...

class ScanZone:
    @staticmethod
    def rectangle(
        name: str, min_x: float, min_y: float, max_x: float, max_y: float
    ) -> ScanZone: ...
    @staticmethod
    def circle(name: str, center_x: float, center_y: float, radius: float) -> ScanZone: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...

class DisasterResponse:
    def __init__(self, config: DisasterConfig) -> None: ...
    def initialize_event(self, x: float, y: float, description: str) -> None: ...
    def add_zone(self, zone: ScanZone) -> None: ...
    def push_csi_data(self, amplitudes: list[float], phases: list[float]) -> None: ...
    def scan_once(self) -> None: ...
    def survivors(self) -> list[Survivor]: ...
    def survivors_by_triage(self, status: TriageStatus) -> list[Survivor]: ...
    def __repr__(self) -> str: ...
